-- ============================================================================
-- ROLLBACK for supabase/migrations/20260830000000_recurring_pickups_v1.sql
--
-- MANUAL USE ONLY. This file is NOT a migration — it lives outside
-- supabase/migrations/ specifically so no tooling ever picks it up and runs it
-- automatically. Review every statement before running any of this by hand in
-- the Supabase SQL editor. Requires the owner's explicit authorization to run
-- for any reason.
--
-- !! DATA LOSS WARNING !!
-- Dropping recurring_schedules PERMANENTLY DESTROYS every schedule's
-- configuration: which customers are enrolled, their frequency, pickup/
-- delivery windows, recurring instructions, and consent timestamp. This
-- cannot be recovered from the bookings table afterward — a generated
-- booking only remembers that it WAS a recurring occurrence (until this
-- script also strips that linkage, below), never the schedule's own
-- settings. If any schedule might still be wanted, export
-- public.recurring_schedules first.
--
-- This script does NOT delete any booking row. Every booking ever
-- generated by a recurring schedule remains in place, in full, exactly as
-- it is today — only its link back to the (now-gone) schedule is removed,
-- and its booking_source is remapped from 'recurring' to 'phone' so it
-- stays a normal, valid, fully auditable booking record after the
-- 'recurring' value is no longer a permitted booking_source.
--
-- The preferred production rollback is disabling cron and reverting the
-- app deployment, NOT running this file — see the two safer levels below,
-- both of which this script's own first step (unscheduling cron, if it
-- exists) is also part of.
-- ============================================================================
begin;

-- 0. Defensive: unschedule the recurring-generation cron job first, if
-- Checkpoint 3's activation migration was ever applied. Guarded so this is
-- a safe no-op in the (expected) case this rollback is used before
-- Checkpoint 3 ever ships — referencing the cron schema/table directly
-- would error outright if the pg_cron extension was never enabled here.
-- The job name below MUST match the one Checkpoint 3's activation
-- migration actually uses (generate_due_recurring_bookings_daily) — if
-- that name ever changes, update it here too.
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'cron') then
    if exists (select 1 from cron.job where jobname = 'generate_due_recurring_bookings_daily') then
      perform cron.unschedule('generate_due_recurring_bookings_daily');
    end if;
  end if;
end $$;

-- 1. Drop the dormant generation function. No data depends on it existing.
drop function if exists public.generate_due_recurring_bookings(date);

-- 2. Must happen before the column drops below: the widened anon policy
-- references recurring_schedule_id/recurring_occurrence_date, and
-- Postgres won't let you drop a column that's still referenced by an
-- existing policy's WITH CHECK.
alter policy "anon can create pending bookings" on public.bookings
  with check (
    status = 'pending'
    and paid = false
    and booking_source = 'website'
    and admin_notes is null
    and confirmed_pickup_date is null
    and confirmed_pickup_time is null
    and confirmed_delivery_date is null
    and confirmed_delivery_time is null
    and actual_weight_lb is null
    and billable_weight_lb is null
    and laundry_charge_cents is null
    and same_day_fee_cents is null
    and surcharge_total_cents = 0
    and surcharge_notes is null
    and quote_status = 'not_started'
    and quote_sent_at is null
    and payment_method is null
    and paid_at is null
    and payment_verified_by is null
    and created_by is null
    and updated_by is null
    and dry_cleaning_item_subtotal_cents is null
    and dry_cleaning_effective_charge_cents is null
    and dry_cleaning_notes is null
  );

-- 3. Remap booking_source = 'recurring' to 'phone' — the closest existing
-- meaning ("staff-initiated, not a customer's own website submission") —
-- while the wider 3-value CHECK is still in place and permits the
-- in-between state. Must run BEFORE the narrower CHECK below is restored:
-- once 'recurring' is no longer a valid value, any row still holding it
-- would make the ADD CONSTRAINT fail outright.
update public.bookings set booking_source = 'phone' where booking_source = 'recurring';

alter table public.bookings drop constraint if exists bookings_booking_source_check;
alter table public.bookings add constraint bookings_booking_source_check
  check (booking_source in ('website', 'phone'));

-- 4. Drop the recurring-linkage columns. Every other column on these
-- rows — name, phone, address, dates, times, status, quote, payment,
-- everything — is completely untouched; only the two recurring-specific
-- columns and the constraint/index tying them together are removed.
alter table public.bookings drop constraint if exists bookings_recurring_fields_check;
drop index if exists public.bookings_recurring_schedule_occurrence_unique_idx;
drop index if exists public.bookings_recurring_schedule_id_idx;

alter table public.bookings
  drop column if exists recurring_occurrence_date,
  drop column if exists recurring_schedule_id;

-- 5. Drop recurring_schedules itself. THIS IS THE IRREVERSIBLE STEP — see
-- the warning banner above. Everything before this point was safe to run
-- even without intending to go this far.
drop table if exists public.recurring_schedules;

commit;
